### ISSUE TITLE
Auto patches to Zephyr when compiling

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#44] opened 2023-08-21 19:12 UTC
There are some patches, for example to upscale native_posix SDL display. 
Would be handy to automatically apply those patches when complinging.

**Comment by vChavezB** [comment] 2023-08-22 19:37
Golioth has a script to run a patch command when using the manifest file

https://github.com/golioth/golioth-zephyr-sdk/blob/main/scripts/west_commands/patch.py

and you can see it in action here

https://github.com/golioth/golioth-zephyr-sdk/blob/cc146c1e0d4f2c666a37da3b6de7cc5902367484/west-ncs.yml#L15

This issue would be related to first setting up a manifest file as mentioned in https://github.com/jakkra/ZSWatch/issues/35

**Comment by ldab** [comment] 2023-11-15 18:02
@jakkra I can only see “ app/zephyr_patches/sdl_upscale.patch” is there another one?

**Comment by Kampi** [comment] 2023-11-15 18:12
@ldab we have a patch for the nPM1300 driver which is necessary for later revisions with the new power management. It´s not checked in in Git, so you can add it if you want

[ntc_fix.patch](https://github.com/jakkra/ZSWatch/files/13367904/ntc_fix.patch)

**Comment by jakkra** [comment] 2023-11-15 18:14
@ldab do note that this sdl patch does not work anymore, that code was refactored. It's not necessary, so it can be removed.

**Comment by ldab** [comment] 2023-11-15 19:01
> @ldab do note that this sdl patch does not work anymore, that code was refactored. It's not necessary, so it can be removed.

both `kscan_sdl.c` and `display_sdl.c` are not required anymore? How to make the screen bigger?

**Comment by jakkra** [comment] 2023-11-15 21:06
> > @ldab do note that this sdl patch does not work anymore, that code was refactored. It's not necessary, so it can be removed.
> 
> both `kscan_sdl.c` and `display_sdl.c` are not required anymore? How to make the screen bigger?

Well they are needed to scale it up, but requires re-doing this patch. But current default not scaled is useable also.

**Comment by Kampi** [comment] 2023-11-23 22:08
@jakkra @ldab 
CI/CD is reporting this

![image](https://github.com/jakkra/ZSWatch/assets/3458587/7700814c-f032-4d02-8a65-e3dbf02174a3)

**Comment by jakkra** [comment] 2023-11-23 23:09
> @jakkra @ldab CI/CD is reporting this
> 
> ![image](https://user-images.githubusercontent.com/3458587/285316113-7700814c-f032-4d02-8a65-e3dbf02174a3.png)

I got a fix incoming.

**Comment by ldab** [comment] 2023-11-24 12:56
Strange, main gives me:

```
-- west build: generating a build system
patching file modules/lvgl/input/lvgl_common_input.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
patching file modules/lvgl/input/lvgl_common_input.h
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
patching file drivers/sensor/npm1300_charger/npm1300_charger.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
```

In order to reproduce I tried:

1. Clean the build folder
2. Pristine build
3. Build again
4. Clean changes on Zephyr repo

Can't reproduce it

**Closed** 2023-11-24 13:24 UTC
Labels: No Hardware Required

**Comment by jakkra** [comment] 2023-11-24 13:25
Fixed now and CI as good. Works locally also for me.
https://github.com/jakkra/ZSWatch/commit/694798a6fd55b2753d6025e603d2a14534c9c692
